# Site settings
title: The Thespian's Commentary
email: 
description: > # this means to ignore newlines until "baseurl:"
  My blog is not a haters blog, but it is simply to critique the world of what we actually call theatre.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "kmott99.github.io" # the base hostname & protocol for your site

github_username: kmott99

# Build settings
markdown: kramdown
